### ISSUE TITLE
Needs to update to php 8

### ISSUE THREAD

**Issue by pixeline** [WonderNetwork/wiuphp#1]
when running Composer require, it complains about the php version:

> Package wondernetwork/wiuphp has requirements incompatible with your PHP version, PHP extensions and Composer version:  
>     - wondernetwork/wiuphp v0.0.4 requires php ^7.4 which does not match your installed version 8.0.30.

**Comment by ellotheth** [comment]
Thanks for the report! We'll take a look at prioritizing this upgrade.
